/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	meterv1alpha1 "github.com/kube-all/api/meter/v1alpha1"
	versioned "github.com/kube-all/client-go/meter/clientset/versioned"
	internalinterfaces "github.com/kube-all/client-go/meter/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/client-go/meter/listers/meter/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MeterInformer provides access to a shared informer and lister for
// Meters.
type MeterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MeterLister
}

type meterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMeterInformer constructs a new informer for Meter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMeterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMeterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMeterInformer constructs a new informer for Meter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMeterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeterV1alpha1().Meters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeterV1alpha1().Meters(namespace).Watch(context.TODO(), options)
			},
		},
		&meterv1alpha1.Meter{},
		resyncPeriod,
		indexers,
	)
}

func (f *meterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMeterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *meterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&meterv1alpha1.Meter{}, f.defaultInformer)
}

func (f *meterInformer) Lister() v1alpha1.MeterLister {
	return v1alpha1.NewMeterLister(f.Informer().GetIndexer())
}
