/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	rbacv1alpha1 "github.com/kube-all/api/rbac/v1alpha1"
	versioned "github.com/kube-all/client-go/rbac/clientset/versioned"
	internalinterfaces "github.com/kube-all/client-go/rbac/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/client-go/rbac/listers/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeUserAPIKeyInformer provides access to a shared informer and lister for
// KubeUserAPIKeys.
type KubeUserAPIKeyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KubeUserAPIKeyLister
}

type kubeUserAPIKeyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKubeUserAPIKeyInformer constructs a new informer for KubeUserAPIKey type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeUserAPIKeyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeUserAPIKeyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKubeUserAPIKeyInformer constructs a new informer for KubeUserAPIKey type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeUserAPIKeyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacV1alpha1().KubeUserAPIKeys().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacV1alpha1().KubeUserAPIKeys().Watch(context.TODO(), options)
			},
		},
		&rbacv1alpha1.KubeUserAPIKey{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeUserAPIKeyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeUserAPIKeyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeUserAPIKeyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rbacv1alpha1.KubeUserAPIKey{}, f.defaultInformer)
}

func (f *kubeUserAPIKeyInformer) Lister() v1alpha1.KubeUserAPIKeyLister {
	return v1alpha1.NewKubeUserAPIKeyLister(f.Informer().GetIndexer())
}
