/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	monitorv1alpha1 "github.com/kube-all/api/monitor/v1alpha1"
	versioned "github.com/kube-all/client-go/monitor/clientset/versioned"
	internalinterfaces "github.com/kube-all/client-go/monitor/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/client-go/monitor/listers/monitor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterDashboardInformer provides access to a shared informer and lister for
// ClusterDashboards.
type ClusterDashboardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterDashboardLister
}

type clusterDashboardInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterDashboardInformer constructs a new informer for ClusterDashboard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterDashboardInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterDashboardInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterDashboardInformer constructs a new informer for ClusterDashboard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterDashboardInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitorV1alpha1().ClusterDashboards().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitorV1alpha1().ClusterDashboards().Watch(context.TODO(), options)
			},
		},
		&monitorv1alpha1.ClusterDashboard{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterDashboardInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterDashboardInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterDashboardInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&monitorv1alpha1.ClusterDashboard{}, f.defaultInformer)
}

func (f *clusterDashboardInformer) Lister() v1alpha1.ClusterDashboardLister {
	return v1alpha1.NewClusterDashboardLister(f.Informer().GetIndexer())
}
