/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	clusterv1alpha1 "github.com/kube-all/api/cluster/v1alpha1"
	versioned "github.com/kube-all/client-go/cluster/clientset/versioned"
	internalinterfaces "github.com/kube-all/client-go/cluster/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kube-all/client-go/cluster/listers/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeployTemplateInformer provides access to a shared informer and lister for
// DeployTemplates.
type DeployTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeployTemplateLister
}

type deployTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDeployTemplateInformer constructs a new informer for DeployTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeployTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeployTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDeployTemplateInformer constructs a new informer for DeployTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeployTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().DeployTemplates().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().DeployTemplates().Watch(context.TODO(), options)
			},
		},
		&clusterv1alpha1.DeployTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *deployTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeployTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deployTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterv1alpha1.DeployTemplate{}, f.defaultInformer)
}

func (f *deployTemplateInformer) Lister() v1alpha1.DeployTemplateLister {
	return v1alpha1.NewDeployTemplateLister(f.Informer().GetIndexer())
}
