/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kube-all/api/rbac/v1alpha1"
	scheme "github.com/kube-all/client-go/rbac/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubeUserAPIKeysGetter has a method to return a KubeUserAPIKeyInterface.
// A group's client should implement this interface.
type KubeUserAPIKeysGetter interface {
	KubeUserAPIKeys() KubeUserAPIKeyInterface
}

// KubeUserAPIKeyInterface has methods to work with KubeUserAPIKey resources.
type KubeUserAPIKeyInterface interface {
	Create(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.CreateOptions) (*v1alpha1.KubeUserAPIKey, error)
	Update(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.UpdateOptions) (*v1alpha1.KubeUserAPIKey, error)
	UpdateStatus(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.UpdateOptions) (*v1alpha1.KubeUserAPIKey, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KubeUserAPIKey, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KubeUserAPIKeyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubeUserAPIKey, err error)
	KubeUserAPIKeyExpansion
}

// kubeUserAPIKeys implements KubeUserAPIKeyInterface
type kubeUserAPIKeys struct {
	client rest.Interface
}

// newKubeUserAPIKeys returns a KubeUserAPIKeys
func newKubeUserAPIKeys(c *RbacV1alpha1Client) *kubeUserAPIKeys {
	return &kubeUserAPIKeys{
		client: c.RESTClient(),
	}
}

// Get takes name of the kubeUserAPIKey, and returns the corresponding kubeUserAPIKey object, and an error if there is any.
func (c *kubeUserAPIKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KubeUserAPIKey, err error) {
	result = &v1alpha1.KubeUserAPIKey{}
	err = c.client.Get().
		Resource("kubeuserapikeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubeUserAPIKeys that match those selectors.
func (c *kubeUserAPIKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubeUserAPIKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KubeUserAPIKeyList{}
	err = c.client.Get().
		Resource("kubeuserapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubeUserAPIKeys.
func (c *kubeUserAPIKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kubeuserapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubeUserAPIKey and creates it.  Returns the server's representation of the kubeUserAPIKey, and an error, if there is any.
func (c *kubeUserAPIKeys) Create(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.CreateOptions) (result *v1alpha1.KubeUserAPIKey, err error) {
	result = &v1alpha1.KubeUserAPIKey{}
	err = c.client.Post().
		Resource("kubeuserapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeUserAPIKey).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubeUserAPIKey and updates it. Returns the server's representation of the kubeUserAPIKey, and an error, if there is any.
func (c *kubeUserAPIKeys) Update(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.UpdateOptions) (result *v1alpha1.KubeUserAPIKey, err error) {
	result = &v1alpha1.KubeUserAPIKey{}
	err = c.client.Put().
		Resource("kubeuserapikeys").
		Name(kubeUserAPIKey.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeUserAPIKey).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kubeUserAPIKeys) UpdateStatus(ctx context.Context, kubeUserAPIKey *v1alpha1.KubeUserAPIKey, opts v1.UpdateOptions) (result *v1alpha1.KubeUserAPIKey, err error) {
	result = &v1alpha1.KubeUserAPIKey{}
	err = c.client.Put().
		Resource("kubeuserapikeys").
		Name(kubeUserAPIKey.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeUserAPIKey).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubeUserAPIKey and deletes it. Returns an error if one occurs.
func (c *kubeUserAPIKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kubeuserapikeys").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubeUserAPIKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kubeuserapikeys").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubeUserAPIKey.
func (c *kubeUserAPIKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubeUserAPIKey, err error) {
	result = &v1alpha1.KubeUserAPIKey{}
	err = c.client.Patch(pt).
		Resource("kubeuserapikeys").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
