/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kube-all/api/monitor/v1alpha1"
	scheme "github.com/kube-all/client-go/monitor/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterDashboardsGetter has a method to return a ClusterDashboardInterface.
// A group's client should implement this interface.
type ClusterDashboardsGetter interface {
	ClusterDashboards() ClusterDashboardInterface
}

// ClusterDashboardInterface has methods to work with ClusterDashboard resources.
type ClusterDashboardInterface interface {
	Create(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.CreateOptions) (*v1alpha1.ClusterDashboard, error)
	Update(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.UpdateOptions) (*v1alpha1.ClusterDashboard, error)
	UpdateStatus(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.UpdateOptions) (*v1alpha1.ClusterDashboard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterDashboard, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterDashboardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterDashboard, err error)
	ClusterDashboardExpansion
}

// clusterDashboards implements ClusterDashboardInterface
type clusterDashboards struct {
	client rest.Interface
}

// newClusterDashboards returns a ClusterDashboards
func newClusterDashboards(c *MonitorV1alpha1Client) *clusterDashboards {
	return &clusterDashboards{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterDashboard, and returns the corresponding clusterDashboard object, and an error if there is any.
func (c *clusterDashboards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterDashboard, err error) {
	result = &v1alpha1.ClusterDashboard{}
	err = c.client.Get().
		Resource("clusterdashboards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterDashboards that match those selectors.
func (c *clusterDashboards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterDashboardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterDashboardList{}
	err = c.client.Get().
		Resource("clusterdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterDashboards.
func (c *clusterDashboards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterDashboard and creates it.  Returns the server's representation of the clusterDashboard, and an error, if there is any.
func (c *clusterDashboards) Create(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.CreateOptions) (result *v1alpha1.ClusterDashboard, err error) {
	result = &v1alpha1.ClusterDashboard{}
	err = c.client.Post().
		Resource("clusterdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDashboard).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterDashboard and updates it. Returns the server's representation of the clusterDashboard, and an error, if there is any.
func (c *clusterDashboards) Update(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.UpdateOptions) (result *v1alpha1.ClusterDashboard, err error) {
	result = &v1alpha1.ClusterDashboard{}
	err = c.client.Put().
		Resource("clusterdashboards").
		Name(clusterDashboard.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDashboard).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterDashboards) UpdateStatus(ctx context.Context, clusterDashboard *v1alpha1.ClusterDashboard, opts v1.UpdateOptions) (result *v1alpha1.ClusterDashboard, err error) {
	result = &v1alpha1.ClusterDashboard{}
	err = c.client.Put().
		Resource("clusterdashboards").
		Name(clusterDashboard.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterDashboard).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterDashboard and deletes it. Returns an error if one occurs.
func (c *clusterDashboards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterdashboards").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterDashboards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterdashboards").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterDashboard.
func (c *clusterDashboards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterDashboard, err error) {
	result = &v1alpha1.ClusterDashboard{}
	err = c.client.Patch(pt).
		Resource("clusterdashboards").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
