/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kube-all/api/monitor/v1alpha1"
	scheme "github.com/kube-all/client-go/monitor/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkspaceDashboardsGetter has a method to return a WorkspaceDashboardInterface.
// A group's client should implement this interface.
type WorkspaceDashboardsGetter interface {
	WorkspaceDashboards() WorkspaceDashboardInterface
}

// WorkspaceDashboardInterface has methods to work with WorkspaceDashboard resources.
type WorkspaceDashboardInterface interface {
	Create(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.CreateOptions) (*v1alpha1.WorkspaceDashboard, error)
	Update(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (*v1alpha1.WorkspaceDashboard, error)
	UpdateStatus(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (*v1alpha1.WorkspaceDashboard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WorkspaceDashboard, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WorkspaceDashboardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceDashboard, err error)
	WorkspaceDashboardExpansion
}

// workspaceDashboards implements WorkspaceDashboardInterface
type workspaceDashboards struct {
	client rest.Interface
}

// newWorkspaceDashboards returns a WorkspaceDashboards
func newWorkspaceDashboards(c *MonitorV1alpha1Client) *workspaceDashboards {
	return &workspaceDashboards{
		client: c.RESTClient(),
	}
}

// Get takes name of the workspaceDashboard, and returns the corresponding workspaceDashboard object, and an error if there is any.
func (c *workspaceDashboards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	result = &v1alpha1.WorkspaceDashboard{}
	err = c.client.Get().
		Resource("workspacedashboards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkspaceDashboards that match those selectors.
func (c *workspaceDashboards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkspaceDashboardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkspaceDashboardList{}
	err = c.client.Get().
		Resource("workspacedashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workspaceDashboards.
func (c *workspaceDashboards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("workspacedashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a workspaceDashboard and creates it.  Returns the server's representation of the workspaceDashboard, and an error, if there is any.
func (c *workspaceDashboards) Create(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.CreateOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	result = &v1alpha1.WorkspaceDashboard{}
	err = c.client.Post().
		Resource("workspacedashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceDashboard).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a workspaceDashboard and updates it. Returns the server's representation of the workspaceDashboard, and an error, if there is any.
func (c *workspaceDashboards) Update(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	result = &v1alpha1.WorkspaceDashboard{}
	err = c.client.Put().
		Resource("workspacedashboards").
		Name(workspaceDashboard.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceDashboard).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *workspaceDashboards) UpdateStatus(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	result = &v1alpha1.WorkspaceDashboard{}
	err = c.client.Put().
		Resource("workspacedashboards").
		Name(workspaceDashboard.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceDashboard).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the workspaceDashboard and deletes it. Returns an error if one occurs.
func (c *workspaceDashboards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("workspacedashboards").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workspaceDashboards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("workspacedashboards").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched workspaceDashboard.
func (c *workspaceDashboards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceDashboard, err error) {
	result = &v1alpha1.WorkspaceDashboard{}
	err = c.client.Patch(pt).
		Resource("workspacedashboards").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
