/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kube-all/api/monitor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkspaceDashboards implements WorkspaceDashboardInterface
type FakeWorkspaceDashboards struct {
	Fake *FakeMonitorV1alpha1
}

var workspacedashboardsResource = schema.GroupVersionResource{Group: "monitor.kubeall.com", Version: "v1alpha1", Resource: "workspacedashboards"}

var workspacedashboardsKind = schema.GroupVersionKind{Group: "monitor.kubeall.com", Version: "v1alpha1", Kind: "WorkspaceDashboard"}

// Get takes name of the workspaceDashboard, and returns the corresponding workspaceDashboard object, and an error if there is any.
func (c *FakeWorkspaceDashboards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(workspacedashboardsResource, name), &v1alpha1.WorkspaceDashboard{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceDashboard), err
}

// List takes label and field selectors, and returns the list of WorkspaceDashboards that match those selectors.
func (c *FakeWorkspaceDashboards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkspaceDashboardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(workspacedashboardsResource, workspacedashboardsKind, opts), &v1alpha1.WorkspaceDashboardList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkspaceDashboardList{ListMeta: obj.(*v1alpha1.WorkspaceDashboardList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkspaceDashboardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workspaceDashboards.
func (c *FakeWorkspaceDashboards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(workspacedashboardsResource, opts))
}

// Create takes the representation of a workspaceDashboard and creates it.  Returns the server's representation of the workspaceDashboard, and an error, if there is any.
func (c *FakeWorkspaceDashboards) Create(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.CreateOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(workspacedashboardsResource, workspaceDashboard), &v1alpha1.WorkspaceDashboard{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceDashboard), err
}

// Update takes the representation of a workspaceDashboard and updates it. Returns the server's representation of the workspaceDashboard, and an error, if there is any.
func (c *FakeWorkspaceDashboards) Update(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(workspacedashboardsResource, workspaceDashboard), &v1alpha1.WorkspaceDashboard{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceDashboard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkspaceDashboards) UpdateStatus(ctx context.Context, workspaceDashboard *v1alpha1.WorkspaceDashboard, opts v1.UpdateOptions) (*v1alpha1.WorkspaceDashboard, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(workspacedashboardsResource, "status", workspaceDashboard), &v1alpha1.WorkspaceDashboard{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceDashboard), err
}

// Delete takes name of the workspaceDashboard and deletes it. Returns an error if one occurs.
func (c *FakeWorkspaceDashboards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(workspacedashboardsResource, name, opts), &v1alpha1.WorkspaceDashboard{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkspaceDashboards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(workspacedashboardsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkspaceDashboardList{})
	return err
}

// Patch applies the patch and returns the patched workspaceDashboard.
func (c *FakeWorkspaceDashboards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(workspacedashboardsResource, name, pt, data, subresources...), &v1alpha1.WorkspaceDashboard{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceDashboard), err
}
