/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kube-all/api/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeployTemplates implements DeployTemplateInterface
type FakeDeployTemplates struct {
	Fake *FakeClusterV1alpha1
}

var deploytemplatesResource = schema.GroupVersionResource{Group: "cluster.kubeall.com", Version: "v1alpha1", Resource: "deploytemplates"}

var deploytemplatesKind = schema.GroupVersionKind{Group: "cluster.kubeall.com", Version: "v1alpha1", Kind: "DeployTemplate"}

// Get takes name of the deployTemplate, and returns the corresponding deployTemplate object, and an error if there is any.
func (c *FakeDeployTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DeployTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(deploytemplatesResource, name), &v1alpha1.DeployTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployTemplate), err
}

// List takes label and field selectors, and returns the list of DeployTemplates that match those selectors.
func (c *FakeDeployTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DeployTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(deploytemplatesResource, deploytemplatesKind, opts), &v1alpha1.DeployTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DeployTemplateList{ListMeta: obj.(*v1alpha1.DeployTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.DeployTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deployTemplates.
func (c *FakeDeployTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(deploytemplatesResource, opts))
}

// Create takes the representation of a deployTemplate and creates it.  Returns the server's representation of the deployTemplate, and an error, if there is any.
func (c *FakeDeployTemplates) Create(ctx context.Context, deployTemplate *v1alpha1.DeployTemplate, opts v1.CreateOptions) (result *v1alpha1.DeployTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(deploytemplatesResource, deployTemplate), &v1alpha1.DeployTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployTemplate), err
}

// Update takes the representation of a deployTemplate and updates it. Returns the server's representation of the deployTemplate, and an error, if there is any.
func (c *FakeDeployTemplates) Update(ctx context.Context, deployTemplate *v1alpha1.DeployTemplate, opts v1.UpdateOptions) (result *v1alpha1.DeployTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(deploytemplatesResource, deployTemplate), &v1alpha1.DeployTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployTemplate), err
}

// Delete takes name of the deployTemplate and deletes it. Returns an error if one occurs.
func (c *FakeDeployTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(deploytemplatesResource, name, opts), &v1alpha1.DeployTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeployTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(deploytemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DeployTemplateList{})
	return err
}

// Patch applies the patch and returns the patched deployTemplate.
func (c *FakeDeployTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DeployTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(deploytemplatesResource, name, pt, data, subresources...), &v1alpha1.DeployTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployTemplate), err
}
